# LASDataset Default Configuration
# Universal dataset for LAS/LAZ point cloud files with automatic tiling

dataset:
  common:
    NAME: LASDataset
    data_root: ../data/FORInstanceV2  # Root folder containing train/val/test subfolders
    tile_size: 6.0       # Tile size in meters
    tile_overlap: 0.5    # Overlap ratio (0-1)
    voxel_size: 0.04     # Voxel size for downsampling
    voxel_max: 80000     # Max points per sample (null for no limit)
    min_points_per_tile: 2000  # Min points to keep a tile during tiling

    # Label configuration
    label_field: semantic_seg  # LAS field for labels ('classification', 'label', 'user_data', or null for unlabeled)
    label_offset: -1  # Offset to apply to labels (e.g., -1 to map [1,2,3] to [0,1,2])

    # Feature configuration
    use_rgb: false        # Include RGB colors
    use_intensity: false  # Include intensity values
    use_return_number: false  # Include return number info

  train:
    split: train
    loop: 30              # Loop through dataset 30 times per epoch
    presample: true       # Presample and cache data
    variable: false       # Fixed number of points
    shuffle: true         # Shuffle points

  val:
    split: val
    presample: true
    variable: false
    shuffle: false

  test:
    split: test
    presample: false
    variable: false
    shuffle: false

# Feature keys (what to use as input)
feature_keys: pos  # Use only XYZ coordinates

# Dataset info (update based on your data)
num_classes: 3     # Number of classes (update for your dataset)
batch_size: 4
val_batch_size: 1

dataloader:
  num_workers: 6
  collate_fn: collate_to_pyg_batch  # Use PyG batching

# Data augmentation
datatransforms:
  train: [PointsToTensor, FixedPoints, RandomDropout, PointCloudScaling, PointCloudXYZAlign, PointCloudRotation, PointCloudJitter]
  val: [PointsToTensor, FixedPoints, PointCloudXYZAlign]
  kwargs:
    num_points: 20000
    gravity_dim: 2
    scale: [0.9, 1.1]
    angle: [0.25, 0.25, 1]  # Rotation angles [x, y, z] in radians
    jitter_sigma: 0.005
    jitter_clip: 0.02
    dropout_ratio: 0.2

# Training configuration
val_fn: validate
ignore_index: null
epochs: 100

cls_weighed_loss: false

criterion_args:
  NAME: CrossEntropy
  label_smoothing: 0.2

optimizer:
  NAME: 'adamw'
  weight_decay: 1.0e-4

# Learning rate scheduler
sched: cosine
warmup_epochs: 0
min_lr: 1.0e-5
lr: 0.01

grad_norm_clip: 10
use_voting: false

# I/O
log_dir: 'forinstancev2'
save_freq: -1  # -1: only save last and best
val_freq: 1

wandb:
  project: PointNeXt-FORInstanceV2
